name: azure-devops-pipeline-agent

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        
      - uses: docker/metadata-action@v3
        name: Docker metadata
        id: docker_meta
        with:
          images: azure-devops-pipeline-agent
          tags: latest

      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        name: Push the Docker image to Docker Hub
        with:
          context: .
          push: true
          tags: steps.docker_meta.outputs.tags